Vagrant.configure("2") do |config|

    config.vm.define "ansible" do |ansible|
      ansible.vm.box = "ubuntu/bionic64"
      ansible.vm.network "private_network", type: "dhcp"
      ansible.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
       vb.cpus = 1
    end
    ansible.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install software-properties-common -y
    sudo apt-add-repository --yes --update ppa:ansible/ansible
    sudo apt install ansible -y
    SHELL
end

    config.vm.define "web01" do |web01|
        web01.vm.box = "geerlingguy/centos7"
        web01.vm.network "private_network", type: "dhcp"
        web01.vm.provider "virtualbox" do |vb|
         vb.memory = "1024"
         vb.cpus = 1
    end
end


     config.vm.define "web02" do |web02|
        web02.vm.box = "geerlingguy/centos7"
        web02.vm.network "private_network", type: "dhcp"
        web02.vm.provider "virtualbox" do |vb|
         vb.memory = "1024"
         vb.cpus = 1
    end
end 

     config.vm.define "db01" do |db01|
      db01.vm.box = "geerlingguy/centos7"
      db01.vm.network "private_network", type: "dhcp"
      db01.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
       vb.cpus = 1
    end
end

  end