---
# tasks file for post-install
- name: Install NTP on CentOS
  yum:
    name: "{{item}}"
    state: present
  when: ansible_distribution == "CentOS"
  loop:
    - ntp
    - wget
    - git
    - zip
    - unzip

- name: Install NTP on Ubuntu
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  loop:
    - ntp
    - wget
    - git
    - zip
    - unzip

- name: Start & enable NTP on RedHat
  service:
    name: ntpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Start & enable NTP on Debian
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Add group
  group:
    name: devops
    state: present

- name: Add users
  user:
    name: "{{item}}"
    state: present
    groups: devops
  loop: "{{usernames}}"
  tags:
    - system

- name: Banner file /etc/motd
  copy:
    content: "This {{ansible_distribution}} is Managed by Ansible. \n"
    dest: /etc/motd

- name: Deploy NTP conf dile for RedHat
  template:
    src: ntp_redhat.conf.j2
    dest: "{{ntp_path}}"
  when: ansible_os_family == "RedHat"
  notify:
    - Restart NTP on RedHat

- name: Deploy NTP conf dile for Debian
  template:
    src: ntp_debian.conf.j2
    dest: "{{ntp_path}}"
  when: ansible_os_family == "Debian"
  notify:
    - Restart NTP on Debian

- name: Dir for devp data
  file:
    path: /opt/devdata
    state: directory
    mode: 0775
  tags:
    - system

- name: Deploy dev data file
  copy:
    src: dev.txt
    dest: /opt/devdata/dev.txt