---
- name: Setup DBServer
  hosts: dbsrvgrp
  become: yes
  vars:
    dbname: groups
    dbuser: devops
    dbpass: admin123
  tasks:
    - debug:
        var: dbname
    - debug:
        msg: "Value of dbuser is {{dbuser}}"
    - name: Install MySQL server
      yum:
        name: mariadb-server
        state: present
    - name: Start & Enable mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Install MySQL-python.x86_64
      yum:
        name: MySQL-python.x86_64
        state: present
    - name: Create a new database with name 'accounts'
      mysql_db:
        name: "{{dbname}}"
        state: present
    - name: Create db user with name 'admin'
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
